server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: cognito-app1
          uri: http://localhost:8081/
          predicates:
            - Path=/app1/**
          filters:
            - RewritePath=/app1/(?<segment>.*),/$\{segment}
        - id: cognito-app2
          uri: http://localhost:8082/
          predicates:
            - Path=/app2/**
          filters:
            - RewritePath=/app2/(?<segment>.*),/$\{segment}

